# Generated by Django 4.0.5 on 2023-07-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculomodel_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculomodel',
            name='categoria',
            field=models.CharField(choices=[('PRT', 'Particular'), ('TRP', 'Transporte'), ('CRG', 'Carga')], default='PRT', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculomodel',
            name='marca',
            field=models.CharField(choices=[('CHE', 'Chevrolet'), ('FIA', 'Fiat'), ('FOR', 'Ford'), ('TOY', 'Toyota')], default='FOR', max_length=20),
        ),
    ]
