# Generated by Django 4.0.5 on 2023-07-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_vehiculomodel_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculomodel',
            name='marca',
            field=models.CharField(choices=[('CHEVROLET', 'Chevrolet'), ('FIAT', 'Fiat'), ('FORD', 'Ford'), ('TOYOTA', 'Toyota')], default='FORD', max_length=20),
        ),
    ]
