# Generated by Django 4.0.5 on 2023-07-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0005_alter_vehiculomodel_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculomodel',
            name='categoria',
            field=models.CharField(choices=[('PARTICULAR', 'Particular'), ('TRANSPORTE', 'Transporte'), ('CARGA', 'Carga')], default='PARTICULAR', max_length=20),
        ),
    ]
