# Generated by Django 4.0.5 on 2023-07-22 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0006_alter_vehiculomodel_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculomodel',
            options={'permissions': [('visualizar_catalogo', 'Puede visualizar_catalogo')]},
        ),
    ]
