# Generated by Django 4.0.5 on 2023-07-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0007_alter_vehiculomodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculomodel',
            options={'permissions': [('visualizar_catalogo', 'Puede visualizar catalogo')]},
        ),
    ]
