# Generated by Django 4.0.5 on 2023-07-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0008_alter_vehiculomodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculomodel',
            options={'permissions': [('visualizar_catalogo', 'Puede visualizar catalogo')], 'verbose_name_plural': 'Vehículos'},
        ),
    ]
